- name: varaiables call from inventory{local}
  hosts: local
  connection: local
  tasks:
  - name: print variables 
    ansible.builtin.debug:
     msg: "My course name is {{ COURSE }}, duration {{ DURATION }} by trainer {{ TRAINER }}"