- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefine variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Ramesh') }}"



- name: Transform string to list
  vars:
    fruits: "apple,banana,orange"
  ansible.builtin.split:
    msg: " fruits are {{ fruits | split (',') }} "