- name: filters
  hosts: local
  connection: local
  tasks:
  # - name: handle undefine variable
  #   ansible.builtin.debug:
  #     msg: "Hello {{ person | default('Ramesh') }}"


- name: convert string to list
  vars:
    fruits: "apple, banana, orange" #String
  ansible.builtin.split:
    msg: "Fruits are: {{ fruits | split(',') }}"