- name: shell vs Command
  hosts: local
  connection: local
  tasks:
  # - name: create file 
  #   ansible.builtin.file:
  #    path: /tmp/output.txt
  #    state: touch

  - name: execute ls command
    # ansible.builtin.command: ls -ltr > /tmp/output.txt
    ansible.builtin.shell: ls -ltr > /tmp/output.txt
   
 - name: execute ls command in command module
   ansible.builtin.command: lsss -ltrssfff
   register: command_result

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ command_result }}"