- name: Create EC2 Instances
  hosts: local
  connection: local
  become: yes
  vars:
    ami_id: ami-09c813fb71547fc4f
    # vpc_id: vpc-0df004bd355d2ac36
    subnet_id: subnet-0e814051cd870f5f7
    sg_id: sg-0edf79ad0013d26e2
    instance_type: t3.micro
    region: us-east-1c
    instances:
    - mysql
    - backend
    - front

  tasks:
  - name: Ensure boto3 and botocore are installed
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3
    loop:
      - boto3
      - botocore


  - name: Create EC2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"  # use lowercase 'name'
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
      region: "{{ region }}"
      wait: yes
    loop: "{{ instances }}"


