- name: varaiables from files
  hosts: local
  connection: local
  vars_prompt:
  - name: COURSE
    prompt: Please enter course name
    private: false  # it is not confidential information
  - name: DURATION
    prompt: Please enter duration in hours
    private: false
  - name: TRAINER
    prompt: Please enter trainer name
    private: false  
  tasks:
  - name: print variables at task level
    ansible.builtin.debug:
     msg: "My course name is {{ COURSE }}, duration {{ DURATION }} by trainer {{ TRAINER }}"