- name: varaiables call from inventory \\\
  hosts: web
  tasks:
  - name: print variables 
    ansible.builtin.debug:
     msg: "My course name is {{ COURSE }}, duration {{ DURATION }} by trainer {{ TRAINER }}"